version: "3"
services:  
  c2d-web:
    build: ../app
    container_name: c2d-web
    image: mancioshell/ocean-c2d-flow-web
    restart: always
    ports:
      - 80:80
    networks:
      backend:
        ipv4_address: 172.15.0.36
    depends_on:
      - c2d-api
    environment:
      API_URI: "http://c2d-api:8000/"